# Generated by Django 2.1.5 on 2019-01-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Energy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='', max_length=200, null=True)),
                ('enroll_date', models.DateTimeField(blank=True, default='', null=True)),
            ],
        ),
    ]
